coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto

ignore:
  - "custom_components/rainpoint/debug.py"
  - "tests/"
